"""empty message

Revision ID: d961dbb65763
Revises: 
Create Date: 2021-03-29 21:39:11.822405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd961dbb65763'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('funds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('paypal', 'card', name='methodtype'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cc_number', sa.String(length=16), nullable=False),
    sa.Column('cvc', sa.String(length=3), nullable=False),
    sa.Column('valid_month', sa.String(length=2), nullable=False),
    sa.Column('valid_year', sa.String(length=2), nullable=False),
    sa.Column('card_type', sa.Enum('master', 'visa', name='cardtype'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_methods')
    op.drop_table('user_payments')
    op.drop_table('transactions')
    # ### end Alembic commands ###
